// Generated by CoffeeScript 1.6.3
(function() {
  var cc;

  cc = function() {
    return _.each(arguments, function(arg) {
      return console.log(arg);
    });
  };

  $(function() {
    var _w;
    _w = $(window);
    $.fn.StoryBoard = function(options) {
      var Wrapper, createSlides, opts, _top;
      opts = _.extend({
        imagepath: 'images/',
        slides: []
      }, options);
      Wrapper = function(bg) {
        return $("<div/>").addClass("scroll-slide-wrapper").css("background", "url(" + opts.imagepath + bg + ") center center fixed no-repeat");
      };
      createSlides = function(slides) {
        var self;
        self = this;
        return _.each(slides, function(slide) {
          var $wrap;
          if (slide.src != null) {
            $wrap = new Wrapper(slide.src);
            return $wrap.appendTo(self);
          }
        });
      };
      _top = 0;
      createSlides.call(this, opts.slides);
      return _w.scroll(function() {
        _top = _w.scrollTop();
        return cc(_top);
      });
    };
    return $("body").StoryBoard({
      slides: [
        {
          src: 'aerial.jpg'
        }
      ]
    });
  });

}).call(this);
